### ISSUE TITLE
No peers

### ISSUE THREAD

**Issue by 3uzbcqje** [ipfs-shipyard/discussify-browser-extension#24]
This is an AWESOME idea! But it doesn't work for me at the moment. I'm just getting a "No peers" message. Using Brave on Ubuntu, for what that's worth.

**Comment by satazor** [comment]
We haven’t tested in Brave, so perhaps there’s some exception occurring there. Thanks for reporting!

**Comment by 3uzbcqje** [comment]
I appear to be having the same issue in Chrome.

**Comment by satazor** [comment]
Are you testing in the same url but in different browsers? It’s normal to say no peers if you are alone in the discussion.

**Comment by 3uzbcqje** [comment]
Yeah, google.com.

**Comment by satazor** [comment]
Alright, I will need to debug once I arrive home. I’m roaming atm.

**Comment by 3uzbcqje** [comment]
Alright. Yeah, perhaps it's just a minor UI/UX issue and not a technical
issue. Maybe instead of "No peers", which is going to be the norm until
this service gets really popular, it should just say nothing and only
inform you if there ARE peers?

**Comment by satazor** [comment]
I'm currently in google.com in Chrome and Chrome incognito and both can see each other. If you can jump in, we can test together too.

> Yeah, perhaps it's just a minor UI/UX issue and not a technical issue. Maybe instead of "No peers"

We are still exploring how to do this correctly, see https://github.com/ipfs-shipyard/pm-discussify/issues/55. To do this properly though, peer-base needs to give us more information about what's happening under the hood in terms of synchronization.

**Comment by 3uzbcqje** [comment]
I've had it open in a tab this whole time. Did you see my comment at https://www.google.com/?

**Comment by satazor** [comment]
Sorry, I think I’ve missed you. I’m there now. You may also reach me on freenode, same nick as the GitHub.

**Comment by satazor** [comment]
I was on google.pt 😂

I'm on google.com now

**Comment by satazor** [comment]
We were able to see each other and discuss on the extension. Can we close this issue?
